### ISSUE TITLE
Error when running process waveform

### ISSUE THREAD

**Issue by dtdangkua** [usgs/groundmotion-processing#695]
Hi,
I run the process waveform command using -e option and got an error message "can't multiply sequence by non-int of type 'float'". See screenshot below.

<img width="982" alt="Screen Shot 2021-04-05 at 12 49 59 PM" src="https://user-images.githubusercontent.com/81981039/113606387-8a105700-960d-11eb-87be-096e8b16855a.png">

Can someone tell me what is the issue here and what do I need to do run it successfully?
I've used the command for different events, and it worked fine.

Environment:
 - OS: macOS 10.14.6
 - Python Version 3.8
- Libcomcat Version 2.0.7
- Numpy Version 1.20.1

Let me know if you need more info. Thanks.

Donny Dangkua

**Comment by emthompson-usgs** [comment]
Hi @dtdangkua, I'll look into this but I probably won't be able to get to it immediately. In the mean time, can you let me know how you installed the software? Did you use the "conda install" option or the install.sh script? I only ask because this looks like something that might have been solved by a change that was made recently that has not yet made its way into the conda package.

**Comment by dtdangkua** [comment]
Hi @emthompson-usgs, I believe I used install.sh script to install it around mid March. How recent was this change made? I typed gmrecords -v, and this is what I got "gmrecords 1.1.8.dev233+gab8a504.d20210406".

**Comment by emthompson-usgs** [comment]
We've made a few changes for dealing with empty data in the last few weeks, and based on the log, it looks like the issue you are getting could be related. Please re-run the install.sh script after doing a `git pull` in the repository and let me know if the problem persists. If it does, please copy/paste the full terminal log into your comment, wrapping the output in a "code block", which is done with triple back ticks, like this:
```
(gmprocess) ~/src/python/groundmotion-processing(master)
↳ $ ls
CODE_OF_CONDUCT.md	README.rst		data			install.sh		tests
CONTRIBUTING.md		azure-pipelines.yml	docs			notebooks		tools
DISCLAIMER.md		build			gmprocess		pyproject.toml
LICENSE.md		code.json		gmprocess.egg-info	requirements.txt
README			dask-worker-space	htmlcov			setup.py
(gmprocess) ~/src/python/groundmotion-processing(master)
↳ $ git pull
Already up to date.
```

**Comment by dtdangkua** [comment]
After doing `git pull` and re-run the install.sh, the problem persists. Below is the terminal log.

```
(gmprocess) bash-3.2$ ls
CODE_OF_CONDUCT.md      README                  code.json               gmprocess.egg-info      requirements.txt
CONTRIBUTING.md         README.rst              dask-worker-space       install.sh              setup.py
DISCLAIMER.md           azure-pipelines.yml     docs                    notebooks               tests
LICENSE.md              build                   gmprocess               pyproject.toml          tools
(gmprocess) bash-3.2$ git pull
remote: Enumerating objects: 44, done.
remote: Counting objects: 100% (44/44), done.
remote: Compressing objects: 100% (13/13), done.
remote: Total 44 (delta 33), reused 38 (delta 31), pack-reused 0
Unpacking objects: 100% (44/44), done.
From https://github.com/usgs/groundmotion-processing
   ab8a504..1bd2249  master     -> origin/master
Updating ab8a504..1bd2249
Fast-forward
 gmprocess/io/global_fetcher.py                    |  5 +++--
 gmprocess/subcommands/arg_dicts.py                |  9 +++++++++
 gmprocess/subcommands/assemble.py                 |  1 +
 gmprocess/subcommands/compute_station_metrics.py  | 10 +++-------
 gmprocess/subcommands/compute_waveform_metrics.py |  8 ++------
 gmprocess/subcommands/download.py                 | 12 +++---------
 gmprocess/subcommands/export_failure_tables.py    |  4 ++--
 gmprocess/subcommands/export_metric_tables.py     |  3 ++-
 gmprocess/subcommands/export_provenance_tables.py |  3 ++-
 gmprocess/subcommands/export_shakemap.py          |  1 +
 gmprocess/subcommands/generate_report.py          |  3 ++-
 gmprocess/subcommands/process_waveforms.py        |  3 ++-
 gmprocess/utils/plot.py                           | 65 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 13 files changed, 97 insertions(+), 30 deletions(-)
```
```
(gmprocess) bash-3.2$ gmrecords process -e hv387802
INFO 2021-04-07 11:00:06 | gmrecords.__init__: Logging level includes INFO.
--------------------------------------------------------------------------------
Project: GMPE_Hawaii 
        Conf Path: /Users/dtdngkua/gmprocess_projects/GMPE_Hawaii/conf
        Data Path: /Users/dtdngkua/gmprocess_projects/GMPE_Hawaii/data
--------------------------------------------------------------------------------
INFO 2021-04-07 11:00:06 | process_waveforms.main: Running subcommand 'process_waveforms'
INFO 2021-04-07 11:00:07 | process_waveforms.main: Processing tag: 20210407160007
INFO 2021-04-07 11:00:07 | process_waveforms._process_event: Processing 'unprocessed' streams for event hv387802...
INFO 2021-04-07 11:00:07 | processing.process_streams: Stream: G.KIP.LH
INFO 2021-04-07 11:00:08 | stationtrace.fail: check_instrument
INFO 2021-04-07 11:00:08 | stationtrace.fail: Not two horizontal components
INFO 2021-04-07 11:00:08 | stationtrace.fail: check_instrument
INFO 2021-04-07 11:00:08 | stationtrace.fail: Not two horizontal components
INFO 2021-04-07 11:00:08 | stationtrace.fail: check_zero_crossings
INFO 2021-04-07 11:00:08 | stationtrace.fail: Zero crossing rate too low.
INFO 2021-04-07 11:00:08 | stationtrace.fail: check_zero_crossings
INFO 2021-04-07 11:00:08 | stationtrace.fail: Zero crossing rate too low.
WARNING 2021-04-07 11:00:08 | warnings._showwarnmsg: /opt/anaconda3/envs/gmprocess/lib/python3.8/site-packages/obspy/core/inventory/response.py:1895: UserWarning: More than one PolesZerosResponseStage encountered. Returning first one found.
  warnings.warn(msg)

INFO 2021-04-07 11:00:08 | stationtrace.fail: snr_check
INFO 2021-04-07 11:00:08 | stationtrace.fail: Failed SNR check; SNR less than threshold.
INFO 2021-04-07 11:00:08 | stationtrace.fail: snr_check
INFO 2021-04-07 11:00:08 | stationtrace.fail: Failed SNR check; SNR less than threshold.
INFO 2021-04-07 11:00:08 | processing.process_streams: Stream: IU.KIP.BH
Traceback (most recent call last):
  File "/opt/anaconda3/envs/gmprocess/bin/gmrecords", line 33, in <module>
    sys.exit(load_entry_point('gmprocess', 'console_scripts', 'gmrecords')())
  File "/Users/dtdngkua/groundmotion-processing/gmprocess/bin/gmrecords.py", line 6, in main
    GMrecordsApp().main()
  File "/Users/dtdngkua/groundmotion-processing/gmprocess/apps/gmrecords.py", line 90, in main
    self.args.func().main(self)
  File "/Users/dtdngkua/groundmotion-processing/gmprocess/subcommands/process_waveforms.py", line 76, in main
    self._process_event(event)
  File "/Users/dtdngkua/groundmotion-processing/gmprocess/subcommands/process_waveforms.py", line 97, in _process_event
    pstreams = process_streams(
  File "/Users/dtdngkua/groundmotion-processing/gmprocess/waveform_processing/processing.py", line 180, in process_streams
    stream = globals()[step_name](stream, **step_args)
  File "/Users/dtdngkua/groundmotion-processing/gmprocess/waveform_processing/windows.py", line 61, in cut
    stime = split_time - sec_before_split
  File "/opt/anaconda3/envs/gmprocess/lib/python3.8/site-packages/obspy/core/utcdatetime.py", line 1041, in __sub__
    return UTCDateTime(ns=self._ns - int(round((value * 1e9))))
TypeError: can't multiply sequence by non-int of type 'float'

```
Let me know if you need anything else.

**Comment by emthompson-usgs** [comment]
I cannot reproduce this error. Here is what I tried to do. Please tell me if you did something different. 

The error you are getting is with station IU.KIP.BH. So first I modified the conf file so that it will retrieve "BH?" stations, because we do not get those by default. I then downloaded data:
```
$ gmrecords download -e hv387802
```
Note, I'm not including all of the terminal messages here because it is very verbose. The important thing is that I ended up with the station that is giving you an error:
```
$ ls data/hv387802/raw/
IU.KIP..BHE__19911023T124958Z__19911023T125728Z.mseed	IU.KIP..BHZ__19911023T124958Z__19911023T125728Z.mseed
IU.KIP..BHN__19911023T124958Z__19911023T125728Z.mseed	IU.KIP.xml
```
I then run assemble: 
```
$ gmrecords assemble -e hv387802
INFO 2021-04-08 09:11:17 | gmrecords.__init__: Logging level includes INFO.
--------------------------------------------------------------------------------
Project: default
	Conf Path: /Users/emthompson/test/atlas/conf
	Data Path: /Users/emthompson/test/atlas/data
--------------------------------------------------------------------------------
INFO 2021-04-08 09:11:17 | assemble.main: Running subcommand 'assemble'
INFO 2021-04-08 09:11:18 | assemble.main: Number of events to assemble: 1
INFO 2021-04-08 09:11:18 | assemble._assemble_event: Starting event: hv387802
1 StationStreams(s) in StreamCollection:
  3 StationTrace(s) in StationStream (passed):
    IU.KIP..BHE | 1991-10-23T12:49:58.587000Z - 1991-10-23T12:57:28.537000Z | 20.0 Hz, 9000 samples (passed)
    IU.KIP..BHZ | 1991-10-23T12:49:58.587000Z - 1991-10-23T12:57:28.537000Z | 20.0 Hz, 9000 samples (passed)
    IU.KIP..BHN | 1991-10-23T12:49:58.587000Z - 1991-10-23T12:57:28.537000Z | 20.0 Hz, 9000 samples (passed)

INFO 2021-04-08 09:11:20 | stream_workspace.addStreams: Adding waveforms for station KIP

The following files have been created:
File type: Workspace
	/Users/emthompson/test/atlas/data/hv387802/workspace.h5
```
And everything seems fine. So I run process: 
```
$ gmrecords process -e hv387802
INFO 2021-04-08 09:12:43 | gmrecords.__init__: Logging level includes INFO.
--------------------------------------------------------------------------------
Project: default
	Conf Path: /Users/emthompson/test/atlas/conf
	Data Path: /Users/emthompson/test/atlas/data
--------------------------------------------------------------------------------
INFO 2021-04-08 09:12:43 | process_waveforms.main: Running subcommand 'process_waveforms'
INFO 2021-04-08 09:12:44 | process_waveforms.main: Processing tag: 20210408151244
INFO 2021-04-08 09:12:44 | process_waveforms._process_event: Processing 'unprocessed' streams for event hv387802...
INFO 2021-04-08 09:12:44 | processing.process_streams: Stream: IU.KIP.BH
INFO 2021-04-08 09:12:45 | processing.process_streams: Finished processing streams.
INFO 2021-04-08 09:12:45 | stream_workspace.addStreams: Adding waveforms for station KIP
No new files created.
```
And as you can see, I don't get any errors. 

So I wonder if this is related to something you've changed in the config file. Can you list all changes you made to the default config file?

**Comment by dtdangkua** [comment]
I got it to work now. You are right, it's because of something that I changed in the config file. It was the "cut" parameter where I put "None" instead of "Null". I will close the issue now. Thanks for your time.
